"""add_logistics_enhanced_fields

Revision ID: 57d47c7e675a
Revises: 58e7c49d5450
Create Date: 2026-01-23 22:40:48.390139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d47c7e675a'
down_revision: Union[str, Sequence[str], None] = '58e7c49d5450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('logistics_material_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_of_measure', sa.String(length=20), nullable=True))

    with op.batch_alter_table('logistics_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_code', sa.String(length=6), nullable=True))
        batch_op.create_foreign_key('fk_logistics_requests_cancelled_by_id_users', 'users', ['cancelled_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logistics_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_logistics_requests_cancelled_by_id_users', type_='foreignkey')
        batch_op.drop_column('confirmation_code')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancelled_by_id')
        batch_op.drop_column('cancellation_reason')

    with op.batch_alter_table('logistics_material_types', schema=None) as batch_op:
        batch_op.drop_column('unit_of_measure')

    op.create_table('system_settings',
    sa.Column('key', sa.VARCHAR(length=50), nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=False)

    # ### end Alembic commands ###
