"""Add session persistence fields to ShiftAssignment

Revision ID: 84fa3644736f
Revises: e63f29fdf057
Create Date: 2026-01-10 17:56:12.874391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84fa3644736f'
down_revision: Union[str, Sequence[str], None] = 'e63f29fdf057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('fiscal_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_in_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_closed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.drop_column('is_closed')
        batch_op.drop_column('closed_at')
        batch_op.drop_column('checked_in_at')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('fiscal_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)

    # ### end Alembic commands ###
